# Generated by Django 5.2.7 on 2025-11-18 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Constituency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('mp', models.CharField(max_length=255)),
                ('party', models.CharField(max_length=255)),
                ('impeachment_vote', models.CharField(max_length=255)),
                ('county', models.CharField(max_length=255)),
                ('budget_vote', models.CharField(max_length=255)),
                ('geom', models.TextField()),
            ],
        ),
    ]
