# Generated by Django 5.2.8 on 2025-11-19 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electionsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constituency',
            name='geom',
            field=models.TextField(blank=True, help_text='Geographic boundary of the ward (WKT/GeoJSON format)', null=True),
        ),
    ]
