# Generated by Django 5.2.8 on 2025-11-24 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electionsapp', '0002_alter_constituency_geom'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                ALTER TABLE electionsapp_constituency
                ALTER COLUMN geom TYPE geometry(MultiPolygon, 4326)
                USING (
                    CASE
                        WHEN geom IS NULL OR btrim(geom) = '' THEN NULL
                        ELSE ST_Multi(
                            ST_SetSRID(
                                ST_GeomFromWKB(decode(geom, 'hex')),
                                4326
                            )
                        )
                    END
                )
            """,
            reverse_sql="""
                ALTER TABLE electionsapp_constituency
                ALTER COLUMN geom TYPE text
                USING (
                    CASE
                        WHEN geom IS NULL THEN NULL
                        ELSE encode(ST_AsEWKB(geom), 'hex')
                    END
                )
            """,
        ),
    ]
