# Generated by Django 5.2.8 on 2025-12-02 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electionsapp', '0004_constituency_election_results_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='constituency',
            name='registered_voters',
            field=models.PositiveIntegerField(blank=True, help_text='Total number of registered voters in the constituency', null=True),
        ),
        migrations.AddField(
            model_name='constituency',
            name='updated_name',
            field=models.CharField(blank=True, help_text='Newly updated constituency name', max_length=255, null=True),
        ),
    ]
